/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frame;

import control.OrderControl;
import control.mainUiControl;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;

/**
 *
 * @author mynla
 */
public class OrderPanel extends javax.swing.JPanel {

    
    JPanel HoiVien = new QuanLyHoiVienJPanel();
    OrderControl control = new OrderControl();
    int selectedDish=-1;
    
    /**
     * Creates new form ManHinhChinhJPanel
     */
    public OrderPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSDangOrder = new javax.swing.JTable();
        cboTableName = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblTotalPayment = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaVocher = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        cboHinhThucThanhToan = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnThanhtoan = new javax.swing.JButton();
        btnSetOrder = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtSDTHoiVien = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnMo = new javax.swing.JButton();
        btnKhoa = new javax.swing.JButton();
        spinnerAmount = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDSMonAn = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnMo3 = new javax.swing.JButton();
        btnKhoa1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Cbbloai = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtTimMonAn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTienKhachMat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTraKhach = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDSOrderDangLam = new javax.swing.JTable();
        btnXoaOrder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrderNote = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        jPanel13.setBackground(new java.awt.Color(255, 204, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CÁC MÓN CÓ TRONG ĐƠN HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 1, 13))); // NOI18N
        jPanel13.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel13.setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel14.setBackground(new java.awt.Color(255, 204, 204));

        tblDSDangOrder.setBackground(new java.awt.Color(255, 204, 204));
        tblDSDangOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Món", "Số lượng", "Gộp Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSDangOrder.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent mouseEvent){
                if(tblDSDangOrder.getSelectedRow()!=-1 && mouseEvent.getClickCount()==2)
                {
                    // code
                    control.removeDishFromOrder(tblDSDangOrder.getSelectedRow(),1);
                    //        JOptionPane.showMessageDialog(null, "2clicked");
                }
            }
        });
        tblDSDangOrder.setColumnSelectionAllowed(true);
        tblDSDangOrder.getTableHeader().setReorderingAllowed(false);
        tblDSDangOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDSDangOrderMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblDSDangOrder);
        tblDSDangOrder.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblDSDangOrder.getColumnModel().getColumnCount() > 0) {
            tblDSDangOrder.getColumnModel().getColumn(0).setResizable(false);
            tblDSDangOrder.getColumnModel().getColumn(1).setResizable(false);
            tblDSDangOrder.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblDSDangOrder.getColumnModel().getColumn(2).setResizable(false);
        }

        cboTableName.setBackground(new java.awt.Color(255, 255, 255));
        cboTableName.setForeground(new java.awt.Color(0, 0, 0));
        cboTableName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách mang về", "Bàn...", " " }));
        cboTableName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboTableNamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("American Typewriter", 1, 13)); // NOI18N
        jLabel6.setText("GIAO ĐẾN BÀN...");

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalPayment.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalPayment.setText("0");
        jPanel7.add(lblTotalPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 6, 80, -1));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Tổng Đơn :");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel5.setText("VND");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboTableName, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(cboTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Voucher");

        txtMaVocher.setBackground(new java.awt.Color(255, 255, 255));
        txtMaVocher.setForeground(new java.awt.Color(0, 0, 0));
        txtMaVocher.setMaximumSize(null);
        txtMaVocher.setMinimumSize(null);
        txtMaVocher.setPreferredSize(null);
        txtMaVocher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaVocherActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setText("Quét");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        cboHinhThucThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        cboHinhThucThanhToan.setForeground(new java.awt.Color(0, 0, 0));
        cboHinhThucThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa chọn", "Chuyển Khoản", "Tiền Mặt" }));
        cboHinhThucThanhToan.setMaximumSize(null);
        cboHinhThucThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHinhThucThanhToanActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Hình thức thanh toán");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMaVocher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboHinhThucThanhToan, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaVocher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(0, 0, 0)
                .addComponent(cboHinhThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnThanhtoan.setBackground(new java.awt.Color(0, 204, 0));
        btnThanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThanhtoan.setText("Tạo hoá đơn");
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        btnSetOrder.setBackground(new java.awt.Color(255, 102, 0));
        btnSetOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSetOrder.setText("Đơn hàng mới");
        btnSetOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetOrderActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("SDT Hội Viên");

        jCheckBox1.setText("Dùng Điểm");

        txtSDTHoiVien.setBackground(new java.awt.Color(255, 255, 255));
        txtSDTHoiVien.setForeground(new java.awt.Color(0, 0, 0));
        txtSDTHoiVien.setMinimumSize(null);
        txtSDTHoiVien.setPreferredSize(null);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDTHoiVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(btnSetOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(txtSDTHoiVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel15.setBackground(new java.awt.Color(255, 204, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH CÁC MÓN HIỆN CÓ SẴN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 1, 13))); // NOI18N
        jPanel15.setMaximumSize(null);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ ĐƠN HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("American Typewriter", 1, 13))); // NOI18N

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Số Lượng thêm/xoá");

        btnMo.setBackground(new java.awt.Color(255, 102, 102));
        btnMo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMo.setForeground(new java.awt.Color(0, 0, 0));
        btnMo.setText("Xoá khỏi đơn");
        btnMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoActionPerformed(evt);
            }
        });

        btnKhoa.setBackground(new java.awt.Color(153, 255, 255));
        btnKhoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhoa.setForeground(new java.awt.Color(51, 51, 51));
        btnKhoa.setText("Thêm vào đơn");
        btnKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaActionPerformed(evt);
            }
        });

        spinnerAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAmountStateChanged(evt);
            }
        });
        spinnerAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spinnerAmountFocusLost(evt);
            }
        });
        spinnerAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spinnerAmountMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerAmount)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnMo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spinnerAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblDSMonAn.setBackground(new java.awt.Color(255, 204, 204));
        tblDSMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Món", "Giá", "Loại", "Ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSMonAn.setColumnSelectionAllowed(true);
        tblDSMonAn.getTableHeader().setReorderingAllowed(false);
        tblDSMonAn.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent mouseEvent){
                if(tblDSMonAn.getSelectedRow()!=-1 && mouseEvent.getClickCount()==2)
                {
                    // code
                    control.addDish(tblDSMonAn.getSelectedRow(),1);
                    //        JOptionPane.showMessageDialog(null, "2clicked");
                }
            }
        });
        tblDSMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSMonAnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblDSMonAnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblDSMonAnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDSMonAnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblDSMonAnMouseReleased(evt);
            }
        });
        tblDSMonAn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDSMonAnKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblDSMonAn);
        tblDSMonAn.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblDSMonAn.getColumnModel().getColumnCount() > 0) {
            tblDSMonAn.getColumnModel().getColumn(1).setMinWidth(150);
            tblDSMonAn.getColumnModel().getColumn(1).setMaxWidth(300);
            tblDSMonAn.getColumnModel().getColumn(2).setMinWidth(50);
            tblDSMonAn.getColumnModel().getColumn(2).setMaxWidth(100);
            tblDSMonAn.getColumnModel().getColumn(3).setMinWidth(150);
            tblDSMonAn.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng Oder", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        btnMo3.setBackground(new java.awt.Color(255, 102, 102));
        btnMo3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMo3.setForeground(new java.awt.Color(0, 0, 0));
        btnMo3.setText("Mở Món");
        btnMo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMo3ActionPerformed(evt);
            }
        });

        btnKhoa1.setBackground(new java.awt.Color(153, 255, 255));
        btnKhoa1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhoa1.setForeground(new java.awt.Color(51, 51, 51));
        btnKhoa1.setText("Khoá Món");
        btnKhoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKhoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMo3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BỘ LỌC TÌM KIẾM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 1, 13))); // NOI18N

        Cbbloai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cbbloai.setForeground(new java.awt.Color(0, 0, 0));
        Cbbloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Món Ăn", "Đồ Uống", "Tráng Miệng" }));

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Loại");

        txtTimMonAn.setBackground(new java.awt.Color(255, 255, 255));
        txtTimMonAn.setForeground(new java.awt.Color(0, 0, 0));
        txtTimMonAn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimMonAnKeyReleased(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Tên Món");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cbbloai, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTimMonAn)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(txtTimMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel12)
                .addGap(0, 0, 0)
                .addComponent(Cbbloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TÍNH TIỀN THỪA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 1, 13))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        txtTienKhachDua.setBackground(new java.awt.Color(102, 102, 102));
        txtTienKhachDua.setForeground(new java.awt.Color(255, 255, 255));
        txtTienKhachDua.setMaximumSize(null);
        txtTienKhachDua.setMinimumSize(null);
        txtTienKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKhachDuaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Tiền khách đưa (VND)");

        txtTienKhachMat.setEditable(false);
        txtTienKhachMat.setBackground(new java.awt.Color(51, 51, 51));
        txtTienKhachMat.setForeground(new java.awt.Color(255, 255, 255));
        txtTienKhachMat.setText("Chưa có");
        txtTienKhachMat.setMargin(null);
        txtTienKhachMat.setMaximumSize(null);

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Tổng tiền trên hoá đơn (VND)");

        txtTraKhach.setEditable(false);
        txtTraKhach.setBackground(new java.awt.Color(51, 51, 51));
        txtTraKhach.setForeground(new java.awt.Color(255, 255, 255));
        txtTraKhach.setText("0");
        txtTraKhach.setMargin(null);
        txtTraKhach.setMaximumSize(null);

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tiền trả lại khách (VND)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))
                        .addGap(181, 181, 181))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(146, 146, 146))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTraKhach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTienKhachDua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(txtTienKhachMat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(txtTienKhachDua, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(txtTienKhachMat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(txtTraKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(255, 204, 204));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH CÁC ĐƠN HÀNG ĐÃ TẠO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 1, 13))); // NOI18N
        jPanel18.setMaximumSize(null);

        tblDSOrderDangLam.setBackground(new java.awt.Color(255, 204, 204));
        tblDSOrderDangLam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID Đơn Hàng", "Ghi chú", "Tổng phí", "Tên bàn", "Trạng thái", "Thời gian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSOrderDangLam.setColumnSelectionAllowed(true);
        tblDSOrderDangLam.getTableHeader().setReorderingAllowed(false);
        tblDSOrderDangLam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDSOrderDangLamMousePressed(evt);
            }
        });
        tblDSOrderDangLam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDSOrderDangLamKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblDSOrderDangLam);
        //tblDSOrderDangLam.addMouseListener(new MouseAdapter(){
            //    public void mousePressed(MouseEvent mouseEvent){
                //    if(tblDSOrderDangLam.getSelectedRow()!=-1 && mouseEvent.getClickCount()==2)
                //    {
                    //        // code
                    //        control.viewPendingOrderClicked(tblDSOrderDangLam.getSelectedRow());
                    ////        JOptionPane.showMessageDialog(null, "2clicked");
                    //    }
                //}
            //});
    tblDSOrderDangLam.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    if (tblDSOrderDangLam.getColumnModel().getColumnCount() > 0) {
        tblDSOrderDangLam.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblDSOrderDangLam.getColumnModel().getColumn(1).setResizable(false);
        tblDSOrderDangLam.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblDSOrderDangLam.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblDSOrderDangLam.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblDSOrderDangLam.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblDSOrderDangLam.getColumnModel().getColumn(5).setPreferredWidth(100);
        tblDSOrderDangLam.getColumnModel().getColumn(6).setPreferredWidth(150);
    }

    btnXoaOrder.setBackground(new java.awt.Color(255, 51, 51));
    btnXoaOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btnXoaOrder.setForeground(new java.awt.Color(51, 51, 51));
    btnXoaOrder.setText("HUỶ / XOÁ ĐƠN HÀNG");
    btnXoaOrder.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnXoaOrderActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
    jPanel18.setLayout(jPanel18Layout);
    jPanel18Layout.setHorizontalGroup(
        jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane4)
        .addComponent(btnXoaOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel18Layout.setVerticalGroup(
        jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel18Layout.createSequentialGroup()
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnXoaOrder))
    );

    jPanel3.setBackground(new java.awt.Color(255, 204, 204));
    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SỬA GHI CHÚ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 1, 13))); // NOI18N

    txtOrderNote.setColumns(20);
    txtOrderNote.setRows(5);
    jScrollPane1.setViewportView(txtOrderNote);

    jButton1.setText("Xoá");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setText("Lưu");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
            .addGap(12, 12, 12))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaVocherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaVocherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaVocherActionPerformed

    private void cboHinhThucThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHinhThucThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboHinhThucThanhToanActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        control.scanQR(this);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        // TODO add your handling code here:
        control.payment();
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void btnSetOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetOrderActionPerformed
        // TODO add your handling code here:
        control.createOrder();

    }//GEN-LAST:event_btnSetOrderActionPerformed

    private void txtTienKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKhachDuaActionPerformed
        // TODO add your handling code here:
        control.calculate();
    }//GEN-LAST:event_txtTienKhachDuaActionPerformed

    private void tblDSMonAnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMonAnMousePressed
        // TODO add your handling code here:
//        control.dishClicked(tblDSMonAn.getSelectedRow());
          selectedDish=tblDSMonAn.getSelectedRow();
    }//GEN-LAST:event_tblDSMonAnMousePressed

    private void tblDSDangOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSDangOrderMousePressed
        // TODO add your handling code here:
        control.orderClicked(tblDSDangOrder.getSelectedRow());
    }//GEN-LAST:event_tblDSDangOrderMousePressed

    private void spinnerAmountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinnerAmountMousePressed
        // TODO add your handling code here:
//        control.changeDishAmount(spinnerAmount.getValue().toString());
    }//GEN-LAST:event_spinnerAmountMousePressed

    private void spinnerAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAmountStateChanged
         // TODO add your handling code here:
        control.changeDishAmount(spinnerAmount);
    }//GEN-LAST:event_spinnerAmountStateChanged

    private void tblDSOrderDangLamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSOrderDangLamMousePressed
        // TODO add your handling code here:
        control.viewPendingOrderClicked(tblDSOrderDangLam.getSelectedRow());
    }//GEN-LAST:event_tblDSOrderDangLamMousePressed

    private void btnXoaOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaOrderActionPerformed
        // TODO add your handling code here:
        control.deletePendingOrderClicked(tblDSOrderDangLam.getSelectedRow());
    }//GEN-LAST:event_btnXoaOrderActionPerformed

    private void btnKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaActionPerformed
        // TODO add your handling code here:
//        control.addDish
        control.addDish(selectedDish,Integer.parseInt(spinnerAmount.getValue().toString()));
        spinnerAmount.setValue(1);
//        selectedDish=-1;
    }//GEN-LAST:event_btnKhoaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        control.setNote(tblDSOrderDangLam.getSelectedRow(),txtOrderNote.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        control.setNote(tblDSOrderDangLam.getSelectedRow(), "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTimMonAnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimMonAnKeyReleased
        // TODO add your handling code here:
        control.search(txtTimMonAn.getText(),Cbbloai.getSelectedItem().toString());
    }//GEN-LAST:event_txtTimMonAnKeyReleased

    private void btnKhoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoa1ActionPerformed
        // TODO add your handling code here:
//        control.lockDish(tblDSMonAn.);
    }//GEN-LAST:event_btnKhoa1ActionPerformed

    private void btnMo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMo3ActionPerformed

    private void btnMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoActionPerformed
        // TODO add your handling code here:
        control.removeDishFromOrder(tblDSDangOrder.getSelectedRow(),Integer.parseInt(spinnerAmount.getValue().toString()));
        spinnerAmount.setValue(1);
    }//GEN-LAST:event_btnMoActionPerformed

    private void spinnerAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinnerAmountFocusLost
        // TODO add your handling code here:
        control.changeDishAmount(spinnerAmount);
    }//GEN-LAST:event_spinnerAmountFocusLost

    private void tblDSOrderDangLamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDSOrderDangLamKeyReleased
        // TODO add your handling code here:
        control.viewPendingOrderClicked(tblDSOrderDangLam.getSelectedRow());
    }//GEN-LAST:event_tblDSOrderDangLamKeyReleased

    private void tblDSMonAnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDSMonAnKeyReleased
        // TODO add your handling code here:
        selectedDish=tblDSMonAn.getSelectedRow();
    }//GEN-LAST:event_tblDSMonAnKeyReleased

    private void tblDSMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMonAnMouseClicked
        // TODO add your handling code here:
        selectedDish=tblDSMonAn.getSelectedRow();
    }//GEN-LAST:event_tblDSMonAnMouseClicked

    private void tblDSMonAnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMonAnMouseReleased
        // TODO add your handling code here:
        selectedDish=tblDSMonAn.getSelectedRow();
    }//GEN-LAST:event_tblDSMonAnMouseReleased

    private void tblDSMonAnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMonAnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDSMonAnMouseExited

    private void tblDSMonAnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSMonAnMouseEntered
        // TODO add your handling code here:
        mainUiControl.closeMenu();
    }//GEN-LAST:event_tblDSMonAnMouseEntered

    private void cboTableNamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboTableNamePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        control.setTable();
    }//GEN-LAST:event_cboTableNamePopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Cbbloai;
    public static javax.swing.JButton btnKhoa;
    public static javax.swing.JButton btnKhoa1;
    public static javax.swing.JButton btnMo;
    public static javax.swing.JButton btnMo3;
    public static javax.swing.JButton btnSetOrder;
    public static javax.swing.JButton btnThanhtoan;
    public static javax.swing.JButton btnXoaOrder;
    public javax.swing.JComboBox<String> cboHinhThucThanhToan;
    public javax.swing.JComboBox<String> cboTableName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel lblTotalPayment;
    public javax.swing.JSpinner spinnerAmount;
    public javax.swing.JTable tblDSDangOrder;
    public javax.swing.JTable tblDSMonAn;
    public javax.swing.JTable tblDSOrderDangLam;
    public javax.swing.JTextField txtMaVocher;
    public javax.swing.JTextArea txtOrderNote;
    public javax.swing.JTextField txtSDTHoiVien;
    public javax.swing.JTextField txtTienKhachDua;
    public javax.swing.JTextField txtTienKhachMat;
    public javax.swing.JTextField txtTimMonAn;
    public javax.swing.JTextField txtTraKhach;
    // End of variables declaration//GEN-END:variables
}
