package Bill;



import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author mynla
 */
public class InBill extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public InBill() {
        initComponents();
    }
    
    public void payment(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Inbill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"cá", "1", "e24567"},
                {"gạo", "2", "4356"},
                {"nước", "3", "410000"}
            },
            new String [] {
                "Tên", "số lượng", "giá"
            }
        ));
        jScrollPane1.setViewportView(bill);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Đường dẫn đến file font chữ tiếng Việt
        String fontPath = "src\\Font_Anh\\UTM Swiss 721 Black Condensed.ttf";

        // Tạo BaseFont từ file font chữ
        BaseFont baseFont = null;
        try {
            baseFont = BaseFont.createFont(fontPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
        } catch (DocumentException | java.io.IOException e) {
            e.printStackTrace();
        }

        // Tạo Font sử dụng BaseFont vừa tạo
        Font vietnameseFont = new Font(baseFont, 12, Font.NORMAL);

        // Tạo đối tượng Document mới
        Document document = new Document();

        try {
            // Thiết lập PdfWriter và mở tài liệu
            PdfWriter.getInstance(document, new FileOutputStream("src\\Bill\\bill.pdf"));
            document.open();

            // Lấy ngày và giờ hiện tại
            DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy");
            Date date = new Date();
            String formattedDate = dateFormat.format(date);

            // Tạo các đoạn văn bản và font chữ
            Paragraph hello = new Paragraph();
            Paragraph wifi = new Paragraph();
            Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
            Font boldFont1 = new Font(Font.FontFamily.HELVETICA, 25, Font.BOLD);

            // Tạo số ngẫu nhiên cho hóa đơn
            Random random = new Random();
            int random1 = 1000000 + random.nextInt(9999999);
            int random2 = 1000000000 + random.nextInt(999999999);

            // Thêm hình ảnh logo vào tài liệu
            Image image2 = Image.getInstance("src\\Font_Anh\\2.png");
            Image QR = Image.getInstance("src\\Font_Anh\\QR.png");
            image2.setAbsolutePosition(500f, 790f);
            image2.scaleAbsolute(100f, 50f);
             QR.setAbsolutePosition(240, 330);
            QR.scaleAbsolute(100, 100);
            document.add(image2);
            // Thêm thông báo cảm ơn và thông tin bổ sung
            hello.add(new com.itextpdf.text.Chunk("Cảm ơn !!", vietnameseFont));
            hello.setAlignment(Element.ALIGN_CENTER);
            hello.setFont(vietnameseFont);
            wifi.add(new com.itextpdf.text.Chunk("WiFi: " + random1));
            wifi.setAlignment(Element.ALIGN_CENTER);
            // Thêm tên cửa hàng và ngày/giờ
            Paragraph text = new Paragraph("NHÓM 4", new Font(boldFont.getBaseFont(), 20, Font.BOLD | Font.NORMAL, vietnameseFont.getColor()));
            text.setAlignment(Element.ALIGN_CENTER);

            document.add(text);
            document.add(new Paragraph("   "));
            document.add(new Paragraph("   "));
            document.add(new Paragraph("   "));
            document.add(new Paragraph(formattedDate));

            // Thêm thông tin hóa đơn
            Paragraph line = new Paragraph("______________________________________________________________________________");
            document.add(new Paragraph("Mã GD: " + random1, vietnameseFont));
            document.add(new Paragraph("Tên: ", vietnameseFont));
            document.add(new Paragraph("Số Điện Thoại: 0" + random2, vietnameseFont));
            line.getFont().setStyle(Font.BOLD);
            document.add(new Paragraph("   "));
            document.add(line);
            document.add(new Paragraph("   "));

            // Thêm bảng chi tiết hàng hóa
            PdfPTable itemsTable = new PdfPTable(3);
            itemsTable.addCell(new PdfPCell(new Phrase("Tên", vietnameseFont)));
            itemsTable.addCell(new PdfPCell(new Phrase("Số Lượng", vietnameseFont)));
            itemsTable.addCell(new PdfPCell(new Phrase("Giá", vietnameseFont)));

            // Điền dữ liệu vào bảng từ dữ liệu hóa đơn
            int rowCount = bill.getRowCount();
            if (rowCount > 0) {
                for (int i = 0; i < rowCount; i++) {
                    try {
                        String id = (String) bill.getValueAt(i, 0);
                        String name = (String) bill.getValueAt(i, 1);
                        String price = (String) bill.getValueAt(i, 2);

                        System.out.println("ID: " + id);

                        itemsTable.addCell(new PdfPCell(new Phrase(id, vietnameseFont)));
                        itemsTable.addCell(new PdfPCell(new Phrase(name, vietnameseFont)));
                        itemsTable.addCell(new PdfPCell(new Phrase(price, vietnameseFont)));

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }

            document.add(itemsTable);

            // Thêm tổng cộng
            document.add(new Paragraph("   "));
            Paragraph Trai = new Paragraph("Giá: " + random1 + " VND", new Font(boldFont.getBaseFont(), boldFont.getSize(), Font.BOLD | Font.NORMAL, vietnameseFont.getColor()));
            Trai.setAlignment(Element.ALIGN_RIGHT);

            document.add(Trai);
            document.add(hello);
            document.add(new Paragraph("   "));
            document.add(wifi);
            document.add(line);
            document.add(QR);
            // Đóng tài liệu
            document.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        // Hiển thị thông báo thành công
        System.out.println("Hóa đơn được tạo thành công.");
        JOptionPane.showMessageDialog(null, "Hóa đơn được tạo thành công.", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bill;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
